language: ruby
cache: bundler

services:
  - postgresql
  - redis-server

before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c "CREATE USER \"tag-rails-graphql\" WITH PASSWORD 'tag-rails-graphql';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS \"tag-rails-graphql_test\";" -U postgres
  - psql -c "CREATE DATABASE \"tag-rails-graphql_test\" ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate

script:
  - bundle exec rubocop app spec --format simple
  - bundle exec rspec spec -fd
  - bundle exec brakeman -q --no-summary
  - bundle exec bundle audit check --update --quiet
# - bundle exec rubycritic --minimum-score 80 --no-browser
